name: Simple Usage

on: workflow_dispatch

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      # - uses: docker://pandoc/core:2.9
      #   with:
      #     args: "--help" # gets appended to pandoc command
# 경로 출력 하기
      - name: Print current directory
        run: pwd
      - name: Print files in current directory
        run: ls -al
      - name: Convert markdown to pdf
        run: pandoc -o output.pdf input.md
      - name: Print files in current directory
        run: ls -al


      
